### ISSUE TITLE
Build 759: Server crash  java.lang.ClassCastException: net.minecraft.entity.monster.EntityCreeper cannot be cast to net.minecraft.entity.player.EntityPlayer         at powercrystals.minefactoryreloaded.block.BlockFactoryFluid.func_71869_a(BlockFactoryFlui

### ISSUE THREAD

**Issue by jalapeno777** [powercrystals/MineFactoryReloaded#116]
java.lang.ClassCastException: net.minecraft.entity.monster.EntityCreeper cannot be cast to net.minecraft.entity.player.EntityPlayer
        at powercrystals.minefactoryreloaded.block.BlockFactoryFluid.func_71869_a(BlockFactoryFluid.java:59)

http://pastebin.com/0rgb8YY5

**Comment by jalapeno777** [comment]
Okay, this apparently occurs when a creeper falls into a pool of milk

**Comment by Yoshi667** [comment]
Yeah that was an oversight of my change to the BlockFactoryFluid.class. What is happening is that a mob is falling into the milk but because it is only checking for EntityPlayer further down in the code it cannot find the specified mob in EntityPlayer.
I have changed it to EntityLiving now and have put in a new PR to fix this issue. 

CAUTION: This means that mobs can now get the positive potion effects from these liquids though!

**Comment by powercrystals** [comment]
That was fixed by the PR this morning, so closing this.

(I'm not concerned by mobs getting mining speed boosts or night vision, but I guess maybe speed might be interesting.)
