### ISSUE TITLE
Meat Packer gets "clogged" with 1 unit of liquid

### ISSUE THREAD

**Issue by jhaskell** [powercrystals/MineFactoryReloaded#150]
Meat packers appear to only be able to process a minimum of 2 millibuckets of meat/slime at a time. If you end up with a single millibucket of liquid inside a meat packer, it cannot process it, and the meat packer does not allow itself to be filled with the "opposite" liquid. 

You can test this by using a liquid router to split up meat/pink slime and outputting liquids to liquiducts. Use one liquiduct to output to two different meat packers. Liquiducts split the incoming liquid evenly between sources, so an even amount of liquid that is not divisible by 4 ends up with an odd number in each meat packer. (e.g.: if 6 units of liquid enter, each get 3.) Once you are down to 1 liquid in each, attempt to pipe in the opposite liquid.

An easy fix for this would likely be to just discard the single millibucket of liquid in the machine, should it ever end up with only one millibucket.

**Comment by powercrystals** [comment]
The real answer for this I have is to just have two meat packers and a liquid router, but that's not that convenient yet either since you need to have the liquid to program the liquid router.

I'm going to leave this open to remind me that this needs to be improved but I'm not going to fix it immediately.
