### ISSUE TITLE
Add unifier support for essence<->LXP

### ISSUE THREAD

**Issue by powercrystals** [powercrystals/MineFactoryReloaded#250]
1 ME = 2 LXP, according to immibis' conversions

**Comment by KirinDave** [comment]
Doesn't this mean that LXP users can double-dip on LXP by using your machine? This seems like it'd make it much easier for LXP users to use the LXP catalyst.

**Comment by bMarc** [comment]
Double dipping is already possible - you can collect both LXP and MFR essence from the same mob kill. But since LXP can't (couldn't) be used to directly spawn mobs, the unbalance was limited.

This would allow an essence production loop (spawn a large slime on exact, let it drop far enough to die, grinder kills the four mid-size slimes. LXP gets xp from all five kills. Costs 500, generates 400 essence directly. Convert LXP for the other 100) and also allows essence production direct from soul shards - both of these acts have been specifically disabled for the essence production, but that effort would become nil and void if LXP was allowed to be converted to MFR Essence.

**Comment by powercrystals** [comment]
With the new grinder setup xp orbs will not spawn no matter how hard they try, so thst should no longer be a problem.

**Comment by KirinDave** [comment]
Awesome news. Thanks.
