### ISSUE TITLE
Deep Liquid Storage

### ISSUE THREAD

**Issue by stephenmac7** [powercrystals/MineFactoryReloaded#323]
Maybe it would be possible to create a deep storage unit, but instead for liquids. Somewhat like the GregTech quantum tank.

**Comment by tpwrules** [comment]
While that would be nice, it would defeat the purpose of the large multiblock tanks from other mods. DSUs don't have the same issue because they can only store one type of item, so you need many to store unique items versus those in chests. Tanks, however, can only store one liquid anyway, so a Deep Liquid Storage would need to be rather expensive to avoid obsoleting traditional tanks.

**Comment by stephenmac7** [comment]
It would, of course have to have the gregtech and te recipes, allowing plenty of room for expense.

**Comment by megamanzteam** [comment]
I was planning to make a similar suggestion. I want a compact tank that can hold about an ocean worth of buckets. Perhaps require power to pump liquids and store them as a balance mechanism?

**Comment by stephenmac7** [comment]
I don't know. Anything but these dreadful iron tanks will satisfy me. However, requiring power to store things doesn't sound like a great idea. Requiring it to put liquid in/out might be a good one, however, it's inconsistent with the DSU.

**Comment by stephenmac7** [comment]
This repo seems to be dead and I'm not playing Minecraft anymore, so I'm going to go ahead and close this issue.
