### ISSUE TITLE
Redstone signal don't stop machine.

### ISSUE THREAD

**Issue by bick88** [powercrystals/MineFactoryReloaded#406]
The machine doesn't receive the Redstone signal when the lever is on the block, but it works when the lever is on a block next to the machine. It's the same issue with Redstone conduit ender IO.
This anomaly appears in both the latest beta build and alpha build.
http://i.imgur.com/Zql3z4d.png

**Comment by ReneM** [comment]
Do you have [Remote IO](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292285) installed?

I had the same problem, turned out RemoteIO-1.7.10-1.8.1.B84-universal.jar was messing with how redstone worked, which meant that redstone signals no longer shut off MFR machines.

It's also mentioned in the [MCF thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292285-remote-io-v1-8-1-its-time-to-think-outside-the?comment=429)

Solution right now is either downgrading Remote IO to B80, or removing the mod.
