### ISSUE TITLE
Latest release: Item Router Crash (interface with BC pipes)

### ISSUE THREAD

**Issue by jalapeno777** [powercrystals/MineFactoryReloaded#69]
This one is from a BC pipe interfacing with two mods so honestly I'm not sure if it's a BC bug, or a Minefactory Reloaded bug.  The short version is when we connect a cargo manager (steve's carts) to an item router via a wooden BC pipe.  It causes an instant server crash.

http://pastebin.com/8emwPv1M

Screenshot of how placement was done

![2013-04-15_21 19 25](https://f.cloud.github.com/assets/3149646/384008/4dfcec3c-a634-11e2-9291-5747425c131c.png)

**Comment by Emys** [comment]
I have not been able to reproduce this with an identical-looking setup. This must depend on your Cargo Manager settings somehow--I wasn't able to reproduce it with multiple item routers either. Looking at the BC code, it seems unlike the that it's actually caused by BC. I think the Abstract Method Error occurs in an inventory that the BC pipe is trying to access:

https://github.com/BuildCraft/BuildCraft/blob/master/common/buildcraft/core/inventory/TransactorVanillaSided.java#L31

edit: this leads me to assume that the problem is in Steve's Carts. I'll look over the Item Router to make sure, but you should probably report that to Steve.

**Comment by Emys** [comment]
Yeah, having taken a look at the item router, I don't see how it could possibly be at fault. You can see the @Override for the method called in TransactorVanillaSided line 31 right here:

https://github.com/powercrystals/MineFactoryReloaded/blob/master/src/powercrystals/minefactoryreloaded/tile/machine/TileEntityItemRouter.java#L178

I'm not sure what Steve's Carts is doing, or why it's failing at runtime rather than compile time, but I'm almost certain that's where the problem is.
