### ISSUE TITLE
RedNet Module

### ISSUE THREAD

**Issue by calclavia** [powercrystals/MineFactoryReloaded#71]
It's be great if the mod could possibly provide modules. Some players (like myself) might only want parts of the mod (e.g RedNet) or something like that. Or, make it configurable. :)

**Comment by powercrystals** [comment]
You can disable machine recipes. You will in the future be able to disable all recipes at once. I will not provide the ability to install only segments of the mod, because my time is finite and that benefits only a tiny portion of users and the mod is incredibly interdependent. You'll have to live with just not using the rest of MFR, sorry.

**Comment by calclavia** [comment]
Would you like a PR to make it into modules? I've done that with ICBM so I know how. :P

**Comment by powercrystals** [comment]
I have no interest in doing this, PR or not.

**Comment by calclavia** [comment]
Ok. NP.
